name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - "*"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-quality:
    uses: ./.github/workflows/reusable-api-quality.yml

  web-quality:
    uses: ./.github/workflows/reusable-web-quality.yml

  cli-quality:
    uses: ./.github/workflows/reusable-cli-quality.yml
